#!/usr/bin/env python3

#	This file is part of PulseEqualizerGui for Kodi.
#
#	Copyright (C) 2021 wastis    https://github.com/wastis/PulseEqualizerGui
#
#	PulseEqualizerGui is free software; you can redistribute it and/or modify
#	it under the terms of the GNU Lesser General Public License as published
#	by the Free Software Foundation; either version 3 of the License,
#	or (at your option) any later version.
#
#

# from kodi source code, create dictionary of it
RemoteKeys= [
			("DISPLAY",213),
			("REVERSE",226),
			("PLAY",234),
			("FORWARD",227),
			("SKIP_MINUS",221),
			("STOP",224),
			("PAUSE",230),
			("SKIP_PLUS",223),
			("TITLE",229),
			("INFO",195),
			("UP",166),
			("DOWN",167),
			("LEFT",169),
			("RIGHT",168),
			("SELECT",11),
			("ENTER",22),
			("SUBTITLE",44),
			("LANGUAGE",45),
			("MENU",247),
			("BACK",216),
			("1",206),
			("2",205),
			("3",204),
			("4",203),
			("5",202),
			("6",201),
			("7",200),
			("8",199),
			("9",198),
			("0",207),
			("POWER",196),
			("MY_TV",49),
			("MY_MUSIC",9),
			("MY_PICTURES",6),
			("MY_VIDEOS",7),
			("RECORD",232),
			("START",37),
			("VOLUME_PLUS",208),
			("VOLUME_MINUS",209),
			("CHANNEL_PLUS",210),
			("CHANNEL_MINUS",211),
			("MUTE",192),
			("RECORDED_TV",101),
			("LIVE_TV",24),
			("STAR",40),
			("HASH",41),
			("CLEAR",249),
			("TELETEXT",250),
			("RED",251),
			("GREEN",252),
			("YELLOW",253),
			("BLUE",254),
			("PLAYLIST",255),
			("GUIDE",50),
			("LIVE_RADIO",248),
			("EPG_SEARCH",246),
			("EJECT",235),
			("CONTENTS_MENU",236),
			("ROOT_MENU",237),
			("TOP_MENU",238),
			("DVD_MENU",239),
			("PRINT",240)
			]

RemoteNames =[
		("left","LEFT"),
		("right","RIGHT"),
		("up","UP"),
		("down","DOWN"),
		("select","SELECT"),
		("back","BACK"),
		("menu","MENU"),
		("info","INFO"),
		("display","DISPLAY"),
		("title","TITLE"),
		("play","PLAY"),
		("pause","PAUSE"),
		("reverse","REVERSE"),
		("forward","FORWARD"),
		("skipplus","SKIP_PLUS"),
		("skipminus","SKIP_MINUS"),
		("stop","STOP"),
		("zero","0"),
		("one","1"),
		("two","2"),
		("three","3"),
		("four","4"),
		("five","5"),
		("six","6"),
		("seven","7"),
		("eight","8"),
		("nine","9"),
		("power","POWER"),
		("mytv","MY_TV"),
		("mymusic","MY_MUSIC"),
		("mypictures","MY_PICTURES"),
		("myvideo","MY_VIDEOS"),
		("record","RECORD"),
		("start","START"),
		("volumeplus","VOLUME_PLUS"),
		("volumeminus","VOLUME_MINUS"),
		("channelplus","CHANNEL_PLUS"),
		("channelminus","CHANNEL_MINUS"),
		("pageplus","CHANNEL_PLUS"),
		("pageminus","CHANNEL_MINUS"),
		("mute","MUTE"),
		("recordedtv","RECORDED_TV"),
		("guide","GUIDE"),
		("livetv","LIVE_TV"),
		("liveradio","LIVE_RADIO"),
		("epgsearch","EPG_SEARCH"),
		("star","STAR"),
		("hash","HASH"),
		("clear","CLEAR"),
		("enter","ENTER"),
		("playlist","PLAYLIST"),
		("teletext","TELETEXT"),
		("red","RED"),
		("green","GREEN"),
		("yellow","YELLOW"),
		("blue","BLUE"),
		("subtitle","SUBTITLE"),
		("language","LANGUAGE"),
		("eject","EJECT"),
		("contentsmenu","CONTENTS_MENU"),
		("rootmenu","ROOT_MENU"),
		("topmenu","TOP_MENU"),
		("dvdmenu","DVD_MENU"),
		("print","PRINT")
		]

VKEYS = [
		("XBMCVK_BACK",0x08,),
		("XBMCVK_TAB",0x09,),
		("XBMCVK_RETURN",0x0D,),
		("XBMCVK_ESCAPE",0x1B,),
		("XBMCVK_SPACE",0x20,),
		("XBMCVK_EXCLAIM",0x21,),
		("XBMCVK_QUOTEDBL",0x22,),
		("XBMCVK_HASH",0x23,),
		("XBMCVK_DOLLAR",0x24,),
		("XBMCVK_PERCENT",0x25,),
		("XBMCVK_AMPERSAND",0x26,),
		("XBMCVK_QUOTE",0x27,),
		("XBMCVK_LEFTPAREN",0x28,),
		("XBMCVK_RIGHTPAREN",0x29,),
		("XBMCVK_ASTERISK",0x2A,),
		("XBMCVK_PLUS",0x2B,),
		("XBMCVK_COMMA",0x2C,),
		("XBMCVK_MINUS",0x2D,),
		("XBMCVK_PERIOD",0x2E,),
		("XBMCVK_SLASH",0x2F,),
		("XBMCVK_0",0x30,),
		("XBMCVK_1",0x31,),
		("XBMCVK_2",0x32,),
		("XBMCVK_3",0x33,),
		("XBMCVK_4",0x34,),
		("XBMCVK_5",0x35,),
		("XBMCVK_6",0x36,),
		("XBMCVK_7",0x37,),
		("XBMCVK_8",0x38,),
		("XBMCVK_9",0x39,),
		("XBMCVK_COLON",0x3A,),
		("XBMCVK_SEMICOLON",0x3B,),
		("XBMCVK_LESS",0x3C,),
		("XBMCVK_EQUALS",0x3D,),
		("XBMCVK_GREATER",0x3E,),
		("XBMCVK_QUESTION",0x3F,),
		("XBMCVK_AT",0x40,),
		("XBMCVK_A",0x41,),
		("XBMCVK_B",0x42,),
		("XBMCVK_C",0x43,),
		("XBMCVK_D",0x44,),
		("XBMCVK_E",0x45,),
		("XBMCVK_F",0x46,),
		("XBMCVK_G",0x47,),
		("XBMCVK_H",0x48,),
		("XBMCVK_I",0x49,),
		("XBMCVK_J",0x4A,),
		("XBMCVK_K",0x4B,),
		("XBMCVK_L",0x4C,),
		("XBMCVK_M",0x4D,),
		("XBMCVK_N",0x4E,),
		("XBMCVK_O",0x4F,),
		("XBMCVK_P",0x50,),
		("XBMCVK_Q",0x51,),
		("XBMCVK_R",0x52,),
		("XBMCVK_S",0x53,),
		("XBMCVK_T",0x54,),
		("XBMCVK_U",0x55,),
		("XBMCVK_V",0x56,),
		("XBMCVK_W",0x57,),
		("XBMCVK_X",0x58,),
		("XBMCVK_Y",0x59,),
		("XBMCVK_Z",0x5A,),
		("XBMCVK_LEFTBRACKET",0x5B,),
		("XBMCVK_BACKSLASH",0x5C,),
		("XBMCVK_RIGHTBRACKET",0x5D,),
		("XBMCVK_CARET",0x5E,),
		("XBMCVK_UNDERSCORE",0x5F,),
		("XBMCVK_BACKQUOTE",0x60,),
		("XBMCVK_NUMPADDIVIDE",0x61,),
		("XBMCVK_NUMPADTIMES",0x62,),
		("XBMCVK_NUMPADMINUS",0x63,),
		("XBMCVK_NUMPADPLUS",0x64,),
		("XBMCVK_NUMPADENTER",0x65,),
		("XBMCVK_NUMPADPERIOD",0x66,),
		("XBMCVK_NUMPAD0",0x70,),
		("XBMCVK_NUMPAD1",0x71,),
		("XBMCVK_NUMPAD2",0x72,),
		("XBMCVK_NUMPAD3",0x73,),
		("XBMCVK_NUMPAD4",0x74,),
		("XBMCVK_NUMPAD5",0x75,),
		("XBMCVK_NUMPAD6",0x76,),
		("XBMCVK_NUMPAD7",0x77,),
		("XBMCVK_NUMPAD8",0x78,),
		("XBMCVK_NUMPAD9",0x79,),
		("XBMCVK_LEFTBRACE",0x7B,),
		("XBMCVK_PIPE",0x7C,),
		("XBMCVK_RIGHTBRACE",0x7D,),
		("XBMCVK_TILDE",0x7E,),
		("XBMCVK_UP",0x80,),
		("XBMCVK_DOWN",0x81,),
		("XBMCVK_LEFT",0x82,),
		("XBMCVK_RIGHT",0x83,),
		("XBMCVK_PAGEUP",0x84,),
		("XBMCVK_PAGEDOWN",0x85,),
		("XBMCVK_INSERT",0x86,),
		("XBMCVK_DELETE",0x87,),
		("XBMCVK_HOME",0x88,),
		("XBMCVK_END",0x89,),
		("XBMCVK_F1",0x90,),
		("XBMCVK_F2",0x91,),
		("XBMCVK_F3",0x92,),
		("XBMCVK_F4",0x93,),
		("XBMCVK_F5",0x94,),
		("XBMCVK_F6",0x95,),
		("XBMCVK_F7",0x96,),
		("XBMCVK_F8",0x97,),
		("XBMCVK_F9",0x98,),
		("XBMCVK_F10",0x99,),
		("XBMCVK_F11",0x9A,),
		("XBMCVK_F12",0x9B,),
		("XBMCVK_F13",0x9C,),
		("XBMCVK_F14",0x9D,),
		("XBMCVK_F15",0x9E,),
		("XBMCVK_F16",0x9F,),
		("XBMCVK_F17",0xA0,),
		("XBMCVK_F18",0xA1,),
		("XBMCVK_F19",0xA2,),
		("XBMCVK_F20",0xA3,),
		("XBMCVK_F21",0xA4,),
		("XBMCVK_F22",0xA5,),
		("XBMCVK_F23",0xA6,),
		("XBMCVK_F24",0xA7,),
		("XBMCVK_BROWSER_BACK",0xB0,),
		("XBMCVK_BROWSER_FORWARD",0xB1,),
		("XBMCVK_BROWSER_REFRESH",0xB2,),
		("XBMCVK_BROWSER_STOP",0xB3,),
		("XBMCVK_BROWSER_SEARCH",0xB4,),
		("XBMCVK_BROWSER_FAVORITES",0xB5,),
		("XBMCVK_BROWSER_HOME",0xB6,),
		("XBMCVK_VOLUME_MUTE",0xB7,),
		("XBMCVK_VOLUME_DOWN",0xB8,),
		("XBMCVK_VOLUME_UP",0xB9,),
		("XBMCVK_MEDIA_NEXT_TRACK",0xBA,),
		("XBMCVK_MEDIA_PREV_TRACK",0xBB,),
		("XBMCVK_MEDIA_STOP",0xBC,),
		("XBMCVK_MEDIA_PLAY_PAUSE",0xBD,),
		("XBMCVK_LAUNCH_MAIL",0xBE,),
		("XBMCVK_LAUNCH_MEDIA_SELECT",0xBF,),
		("XBMCVK_LAUNCH_APP1",0xC0,),
		("XBMCVK_LAUNCH_APP2",0xC1,),
		("XBMCVK_LAUNCH_FILE_BROWSER",0xC2,),
		("XBMCVK_LAUNCH_MEDIA_CENTER",0xC3,),
		("XBMCVK_MEDIA_REWIND",0xC4,),
		("XBMCVK_MEDIA_FASTFORWARD",0xC5,),
		("XBMCVK_MEDIA_RECORD",0xC6,),
		("XBMCVK_LCONTROL",0xD0,),
		("XBMCVK_RCONTROL",0xD1,),
		("XBMCVK_LSHIFT",0xD2,),
		("XBMCVK_RSHIFT",0xD3,),
		("XBMCVK_LMENU",0xD4,),
		("XBMCVK_RMENU",0xD5,),
		("XBMCVK_LWIN",0xD6,),
		("XBMCVK_RWIN",0xD7,),
		("XBMCVK_MENU",0xD8,),
		("XBMCVK_CAPSLOCK",0xD9,),
		("XBMCVK_NUMLOCK",0xDA,),
		("XBMCVK_PRINTSCREEN",0xDB,),
		("XBMCVK_SCROLLLOCK",0xDC,),
		("XBMCVK_PAUSE",0XDD,),
		("XBMCVK_POWER",0XDE,),
		("XBMCVK_SLEEP",0XDF,),
		("XBMCVK_GUIDE",0xE0,),
		("XBMCVK_SETTINGS",0xE1,),
		("XBMCVK_INFO",0xE2,),
		("XBMCVK_RED",0xE3,),
		("XBMCVK_GREEN",0xE4,),
		("XBMCVK_YELLOW",0xE5,),
		("XBMCVK_BLUE",0xE6,),
		("XBMCVK_ZOOM",0xE7,),
		("XBMCVK_TEXT",0xE8,),
		("XBMCVK_FAVORITES",0xE9,),
		("XBMCVK_HOMEPAGE",0xEA,),
		("XBMCVK_CONFIG",0xEB,),
		("XBMCVK_EPG",0xEC,),
		("XBMCVK_LAST",0xFF)
		]

kbdkeys =  [
		("XBMCVK_BACK","backspace"),
		("XBMCVK_TAB","tab"),
		("XBMCVK_RETURN","return"),
		("XBMCVK_ESCAPE","escape"),
		("XBMCVK_0","zero"),
		("XBMCVK_1","one"),
		("XBMCVK_2","two"),
		("XBMCVK_3","three"),
		("XBMCVK_4","four"),
		("XBMCVK_5","five"),
		("XBMCVK_6","six"),
		("XBMCVK_7","seven"),
		("XBMCVK_8","eight"),
		("XBMCVK_9","nine"),
		("XBMCVK_A","a"),
		("XBMCVK_B","b"),
		("XBMCVK_C","c"),
		("XBMCVK_D","d"),
		("XBMCVK_E","e"),
		("XBMCVK_F","f"),
		("XBMCVK_G","g"),
		("XBMCVK_H","h"),
		("XBMCVK_I","i"),
		("XBMCVK_J","j"),
		("XBMCVK_K","k"),
		("XBMCVK_L","l"),
		("XBMCVK_M","m"),
		("XBMCVK_N","n"),
		("XBMCVK_O","o"),
		("XBMCVK_P","p"),
		("XBMCVK_Q","q"),
		("XBMCVK_R","r"),
		("XBMCVK_S","s"),
		("XBMCVK_T","t"),
		("XBMCVK_U","u"),
		("XBMCVK_V","v"),
		("XBMCVK_W","w"),
		("XBMCVK_X","x"),
		("XBMCVK_Y","y"),
		("XBMCVK_Z","z"),
		("XBMCVK_SPACE","space"),
		("XBMCVK_EXCLAIM","exclaim"),
		("XBMCVK_QUOTEDBL","doublequote"),
		("XBMCVK_HASH","hash"),
		("XBMCVK_DOLLAR","dollar"),
		("XBMCVK_PERCENT","percent"),
		("XBMCVK_AMPERSAND","ampersand"),
		("XBMCVK_QUOTE","quote"),
		("XBMCVK_LEFTPAREN","leftbracket"),
		("XBMCVK_RIGHTPAREN","rightbracket"),
		("XBMCVK_ASTERISK","asterisk"),
		("XBMCVK_PLUS","plus"),
		("XBMCVK_COMMA","comma"),
		("XBMCVK_MINUS","minus"),
		("XBMCVK_PERIOD","period"),
		("XBMCVK_SLASH","forwardslash"),
		("XBMCVK_COLON","colon"),
		("XBMCVK_SEMICOLON","semicolon"),
		("XBMCVK_LESS","lessthan"),
		("XBMCVK_EQUALS","equals"),
		("XBMCVK_GREATER","greaterthan"),
		("XBMCVK_QUESTION","questionmark"),
		("XBMCVK_AT","at"),
		("XBMCVK_LEFTBRACKET","opensquarebracket"),
		("XBMCVK_BACKSLASH","backslash"),
		("XBMCVK_RIGHTBRACKET","closesquarebracket"),
		("XBMCVK_CARET","caret"),
		("XBMCVK_UNDERSCORE","underline"),
		("XBMCVK_BACKQUOTE","leftquote"),
		("XBMCVK_LEFTBRACE","openbrace"),
		("XBMCVK_PIPE","pipe"),
		("XBMCVK_RIGHTBRACE","closebrace"),
		("XBMCVK_TILDE","tilde"),
		("XBMCVK_NUMPAD0","numpadzero"),
		("XBMCVK_NUMPAD1","numpadone"),
		("XBMCVK_NUMPAD2","numpadtwo"),
		("XBMCVK_NUMPAD3","numpadthree"),
		("XBMCVK_NUMPAD4","numpadfour"),
		("XBMCVK_NUMPAD5","numpadfive"),
		("XBMCVK_NUMPAD6","numpadsix"),
		("XBMCVK_NUMPAD7","numpadseven"),
		("XBMCVK_NUMPAD8","numpadeight"),
		("XBMCVK_NUMPAD9","numpadnine"),
		("XBMCVK_NUMPADDIVIDE","numpaddivide"),
		("XBMCVK_NUMPADTIMES","numpadtimes"),
		("XBMCVK_NUMPADMINUS","numpadminus"),
		("XBMCVK_NUMPADPLUS","numpadplus"),
		("XBMCVK_NUMPADENTER","enter"),
		("XBMCVK_NUMPADPERIOD","numpadperiod"),
		("XBMCVK_BROWSER_BACK","browser_back"),
		("XBMCVK_BROWSER_FORWARD","browser_forward"),
		("XBMCVK_BROWSER_REFRESH","browser_refresh"),
		("XBMCVK_BROWSER_STOP","browser_stop"),
		("XBMCVK_BROWSER_SEARCH","browser_search"),
		("XBMCVK_BROWSER_FAVORITES","browser_favorites"),
		("XBMCVK_BROWSER_HOME","browser_home"),
		("XBMCVK_VOLUME_MUTE","volume_mute"),
		("XBMCVK_VOLUME_DOWN","volume_down"),
		("XBMCVK_VOLUME_UP","volume_up"),
		("XBMCVK_MEDIA_NEXT_TRACK","next_track"),
		("XBMCVK_MEDIA_PREV_TRACK","prev_track"),
		("XBMCVK_MEDIA_STOP","stop"),
		("XBMCVK_MEDIA_PLAY_PAUSE","play_pause"),
		("XBMCVK_MEDIA_REWIND","rewind"),
		("XBMCVK_MEDIA_FASTFORWARD","fastforward"),
		("XBMCVK_LAUNCH_MAIL","launch_mail"),
		("XBMCVK_LAUNCH_MEDIA_SELECT","launch_media_select"),
		("XBMCVK_LAUNCH_APP1","launch_app1_pc_icon"),
		("XBMCVK_LAUNCH_APP2","launch_app2_pc_icon"),
		("XBMCVK_LAUNCH_FILE_BROWSER","launch_file_browser"),
		("XBMCVK_LAUNCH_MEDIA_CENTER","launch_media_center"),
		("XBMCVK_MEDIA_PLAY_PAUSE","play_pause"),
		("XBMCVK_MEDIA_STOP","stop"),
		("XBMCVK_MEDIA_REWIND","rewind"),
		("XBMCVK_MEDIA_FASTFORWARD","fastforward"),
		("XBMCVK_MEDIA_RECORD","record"),
		("XBMCVK_F1","f1"),
		("XBMCVK_F2","f2"),
		("XBMCVK_F3","f3"),
		("XBMCVK_F4","f4"),
		("XBMCVK_F5","f5"),
		("XBMCVK_F6","f6"),
		("XBMCVK_F7","f7"),
		("XBMCVK_F8","f8"),
		("XBMCVK_F9","f9"),
		("XBMCVK_F10","f10"),
		("XBMCVK_F11","f11"),
		("XBMCVK_F12","f12"),
		("XBMCVK_F13","f13"),
		("XBMCVK_F14","f14"),
		("XBMCVK_F15","f15"),
		("XBMCVK_UP","up"),
		("XBMCVK_DOWN","down"),
		("XBMCVK_RIGHT","right"),
		("XBMCVK_LEFT","left"),
		("XBMCVK_INSERT","insert"),
		("XBMCVK_DELETE","delete"),
		("XBMCVK_HOME","home"),
		("XBMCVK_END","end"),
		("XBMCVK_PAGEUP","pageup"),
		("XBMCVK_PAGEDOWN","pagedown"),
		("XBMCVK_NUMLOCK","numlock"),
		("XBMCVK_CAPSLOCK","capslock"),
		("XBMCVK_RSHIFT","rightshift"),
		("XBMCVK_LSHIFT","leftshift"),
		("XBMCVK_RCONTROL","rightctrl"),
		("XBMCVK_LCONTROL","leftctrl"),
		("XBMCVK_LMENU","leftalt"),
		("XBMCVK_LWIN","leftwindows"),
		("XBMCVK_RWIN","rightwindows"),
		("XBMCVK_MENU","menu"),
		("XBMCVK_PAUSE","pause"),
		("XBMCVK_SCROLLLOCK","scrolllock"),
		("XBMCVK_PRINTSCREEN","printscreen"),
		("XBMCVK_POWER","power"),
		("XBMCVK_SLEEP","sleep"),
		("XBMCVK_GUIDE","guide"),
		("XBMCVK_SETTINGS","settings"),
		("XBMCVK_INFO","info"),
		("XBMCVK_RED","red"),
		("XBMCVK_GREEN","green"),
		("XBMCVK_YELLOW","yellow"),
		("XBMCVK_BLUE","blue"),
		("XBMCVK_ZOOM","zoom"),
		("XBMCVK_TEXT","text"),
		("XBMCVK_FAVORITES","favorites"),
		("XBMCVK_HOMEPAGE","homepage"),
		("XBMCVK_CONFIG","config"),
		("XBMCVK_EPG","epg")
		]

t_name = {
	"one":"1",
	"two":"2",
	"three":"3",
	"four":"4",
	"five":"5",
	"six":"6",
	"seven":"7",
	"eight":"8",
	"nine":"9",
	"zero":"0",
	"star":"*",
	"hash":"#",
	"numpaddivide":"NP /",
	"numpadtimes":"NP *",
	"numpadminus":"NP -",
	"numpadplus":"NP +",
	"numpadzero":"NP 0",
	"numpadone":"NP 1",
	"numpadtwo":"NP 2",
	"numpadthree":"NP 3",
	"numpadfour":"NP 4",
	"numpadfive":"NP 5",
	"numpadsix":"NP 6",
	"numpadseven":"NP 7",
	"numpadeight":"NP 8",
	"numpadnine":"NP 9",
	"openbrace":"{",
	"pipe":"|",
	"closebrace":"}",
	"tilde":"~",
	"f1":"f1",
	"f2":"f2",
	"f3":"f3",
	"f4":"f4",
	"f5":"f5",
	"f6":"f6",
	"f7":"f7",
	"f8":"f8",
	"f9":"f9",
	"f10":"f10",
	"f11":"f11",
	"f12":"f12",
	"f13":"f13",
	"f14":"f14",
	"f15":"f15",
}

#assing translation id
t_tr = {
	"back":32800,
	"backspace":32801,
	"blue":32802,
	"browser_back":32803,
	"browser_favorites":32804,
	"browser_forward":32805,
	"browser_home":32806,
	"browser_refresh":32807,
	"browser_search":32808,
	"browser_stop":32809,
	"capslock":32810,
	"clear":32811,
	"config":32812,
	"contentsmenu":32813,
	"delete":32814,
	"display":32815,
	"down":32816,
	"dvdmenu":32817,
	"eject":32818,
	"end":32819,
	"enter":32820,
	"epg":32821,
	"epgsearch":32822,
	"escape":32823,
	"fastforward":32824,
	"favorites":32825,
	"forward":32826,
	"green":32827,
	"guide":32828,
	"home":32829,
	"homepage":32830,
	"info":32831,
	"insert":32832,
	"language":32833,
	"launch_app1_pc_icon":32834,
	"launch_app2_pc_icon":32835,
	"launch_file_browser":32836,
	"launch_mail":32837,
	"launch_media_center":32838,
	"launch_media_select":32839,
	"left":32840,
	"leftalt":32841,
	"leftctrl":32842,
	"leftshift":32843,
	"leftwindows":32844,
	"liveradio":32845,
	"livetv":32846,
	"menu":32847,
	"mute":32848,
	"mymusic":32849,
	"mypictures":32850,
	"mytv":32851,
	"myvideo":32852,
	"next_track":32853,
	"numlock":32854,
	"numpadperiod":32855,
	"pagedown":32856,
	"pageminus":32857,
	"pageplus":32858,
	"pageup":32859,
	"pause":32860,
	"play":32861,
	"play_pause":32862,
	"playlist":32863,
	"power":32864,
	"prev_track":32865,
	"print":32866,
	"printscreen":32867,
	"record":32868,
	"recordedtv":32869,
	"red":32870,
	"return":32871,
	"reverse":32872,
	"rewind":32873,
	"right":32874,
	"rightctrl":32875,
	"rightshift":32876,
	"rightwindows":32877,
	"rootmenu":32878,
	"scrolllock":32879,
	"select":32880,
	"settings":32881,
	"skipminus":32882,
	"skipplus":32883,
	"sleep":32884,
	"space":32885,
	"start":32886,
	"stop":32887,
	"subtitle":32888,
	"tab":32889,
	"teletext":32890,
	"text":32891,
	"title":32892,
	"topmenu":32893,
	"up":32894,
	"volume_down":32895,
	"volume_mute":32896,
	"volume_up":32897,
	"volumeminus":32898,
	"volumeplus":32899,
	"yellow":32900,
	"zoom":32901
}

name_index = {}
trans_names = {}

for name,vname in RemoteNames:
	name_index[vname] = name

remote_index = {}
for vname, code in RemoteKeys:
	try:
		if code in remote_index:
			print("double code",code)
			continue
		if name_index[vname] in t_name:
			remote_index[code] = {"name":name_index[vname], "char":t_name[name_index[vname]]}
		else:
			remote_index[code] = {"name":name_index[vname], "tr":t_tr[name_index[vname]]}
	except KeyError:
		print(vname, "not found")

name_index = {}
print("RemoteIndex=",remote_index)

for key, val in list(remote_index.items()):
	if "char" in val: continue
	trans_names[val["name"]]= val["name"]

for vname,name in kbdkeys:
	name_index[vname] = name

remote_index = {}
for vname, code in VKEYS:
	try:
		if code in remote_index:
			print("double code",code)
			continue
		if code > 32 and code < 97:
			remote_index[code] = {"name":name_index[vname], "char":chr(code)}
		else:
			if name_index[vname] in t_name:
				remote_index[code] = {"name":name_index[vname], "char":t_name[name_index[vname]]}
			else:
				remote_index[code] = {"name":name_index[vname], "tr":t_tr[name_index[vname]]}

	except KeyError:
		print(vname, "not found")

print("KeyIndex=",remote_index)

for key, val in list(remote_index.items()):
	if "char" in val: continue
	trans_names[val["name"]]= val["name"]

for key,val in list(t_tr.items()):
	print('\nmsgctxt "#{}"\nmsgid "{}"\nmsgstr "{}"'.format(val,key,key))
